- 結果画面のグラフをレーダーチャートに変更
YanaiShohei/intern-yanai pull request #62
Opened 2021-12-20 15:07 UTC by YanaiShohei

- 問題のジャンル別の正解数をカウントができるように変更
- 結果画面のグラフをレーダーチャートに変更

2021-12-21 02:31 UTC, hikaru-nakamura-thedott commented
コンフリクトが起きてるので解決してくださーい。

2021-12-21 05:35 UTC, hikaru-nakamura-thedott commented
@YanaiShohei 
ジャンルごとに正解数をカウントするオブジェクトが宣言されていますが、これらの変数名やジャンル名はまだ決めないんですか？
https://github.com/YanaiShohei/intern-yanai/pull/62/files#diff-43e48298f803a0385d05f1340fc02101e754484b84f22f3ceafaecfbd5d9c9a4R16-R23

2021-12-21 06:00 UTC, hikaru-nakamura-thedott commented
result画面に行った時に点数が表示されてないので直してくださーい。
コンソールに出てるエラーも見てねー。

2021-12-21 07:13 UTC, YanaiShohei commented
@hikaru-nakamura-thedott 
ジャンルの変数名は、まだ出題する問題のジャンルが決めきれていないので出題するジャンルが決まったら変更する予定です。

2021-12-21 07:27 UTC, YanaiShohei commented
result画面の点数なのですが、上のurlから飛んでしまうと表示されないようです。
title画面から開始ボタンを押す→question画面で問題を解き終える。→result画面
の手順なら点数が表示されました。

2021-12-21 08:23 UTC, hikaru-nakamura-thedott commented
@YanaiShohei 
> ジャンルの変数名は、まだ出題する問題のジャンルが決めきれていないので、後のissueの時に変更しようと思っています。

承知しました。
issueの内容に対して、実際の更新内容が中途半端に飛躍してるので、この辺はごちゃごちゃしないように早めに決めた方がいいですね。

中途半端な修正を行うと以下のようなデメリットもあるので、issueごとにキリのいいところまでやりましょう。
- コミット内容と実際の修正・更新に乖離が生まれやすくなるので後々変更が見づらくなる
- バグの原因
- いらないコードが残ってしまう

> result画面の点数表示で修正しようとしたのですが、上のrouterLink？から飛んでしまうと表示されないかもしれないです。
title画面から開始ボタンを押す→question画面で問題を解き終える。→result画面
の手順なら点数が表示されました。

挙動確認しました。確かにquestion -> resultなら正常に動きました。

2021-12-21 08:31 UTC, hikaru-nakamura-thedott commented
@YanaiShohei 
また何点か確認・指摘です。

1. 正解するまで次の問題に遷移しない仕様でしたっけ？
    - これだと正解数カウントする意味がないような...

https://user-images.githubusercontent.com/86763776/146894598-4da1983d-3fea-406f-b8fd-ffccc6bf510f.mov

2. ジャンルごとのカウント、問題を一周したらリセットしないんですか？
3. おそらく以前にデバッグした時にあちこちでconsole.log出力してますが、もう必要のなくなったものは削除してください。
    - 本当に必要なconsole.logが要らないのに紛れて見つけづらくなります。
    - 今のうちに綺麗にしましょう。

2021-12-21 08:50 UTC, hikaru-nakamura-thedott requested changes
細かいところ見つけてしまいました。

2021-12-21 08:50 UTC, hikaru-nakamura-thedott commented on app/src/app/question/question.component.ts
> +import { Quiz, Choice, QUIZ_DATA, } from 'src/app/const/quiz';
ここのカンマ必要？

2021-12-21 08:50 UTC, hikaru-nakamura-thedott commented on app/src/app/services/quiz.service.ts
> +import { ChildrenOutletContexts, Router } from '@angular/router';
ChildrenOutletContexts 使ってる？
使ってないなら削除しましょう。

2021-12-21 08:50 UTC, hikaru-nakamura-thedott commented on app/src/app/services/quiz.service.ts
> +  // 正解した問題をカウントする
ナイスコメント 👍

2021-12-21 08:50 UTC, hikaru-nakamura-thedott commented on app/src/app/const/quiz.ts
> +  category: string;
ジャンルなの？カテゴリなの？

2021-12-21 08:50 UTC, hikaru-nakamura-thedott commented on app/src/app/question/question.component.ts
> +
ここはコメントも書いてあるし、改行ない方がいいねー

2022-01-05 09:32 UTC, hikaru-nakamura-thedott requested changes

2022-01-05 09:32 UTC, hikaru-nakamura-thedott commented on app/src/app/const/quiz.ts
> +  category: string;
これはカテゴリーになりそうだね。

2022-01-05 09:32 UTC, hikaru-nakamura-thedott commented on app/src/app/result/result.component.html
> +<div style="height:400px; width:400px">
おお！すばらしい！
この書き方 `<div width="400" height="400">` はhtml5では非推奨の書き方になっているので、styleプロパティを使う形にしてくれて嬉しいです！
時間があったら、cssファイルに移動するとさらに良いですね！

2022-01-05 09:32 UTC, hikaru-nakamura-thedott commented on app/src/app/services/quiz.service.ts
> +        ++this.correctCategoryCount.gen2020
連想配列を使っているので、以下のように書き換えても同じ結果になります！
`correctCategoryCount.gen2020`  -> `correctCategoryCount['gen2020']`
これを利用してこのif文の連続をもっと短く書いてみましょう！

2022-01-12 10:57 UTC, hikaru-nakamura-thedott commented on app/src/app/services/quiz.service.ts
> +        ++this.correctCategoryCount.gen2020
通話で話したようなことをやろうとすると、
>++this.correctCategoryCount[this.quizList[this.quizCount].category]

「this.correctCategoryCountのkeyの方が何型か指定されていないからダメ！」みたいな感じで怒られる。
<img width="1680" alt="スクリーンショット 2022-01-12 19 45 27" src="https://user-images.githubusercontent.com/86763776/149126414-3fc18756-a31d-4704-944a-571ffb8d6b2c.png">


this.correctCategoryCountのkeyの型を定義してあげましょう。
ついでにnumber型の値を持つことも定義してあげます。

<img width="463" alt="スクリーンショット 2022-01-12 19 51 52" src="https://user-images.githubusercontent.com/86763776/149126952-ab38b0bc-873d-4e6a-87b3-28efbd52b150.png">

このようにすることで `++this.correctCategoryCount[this.quizList[this.quizCount].category]` でアクセスできるようになります。

2022-01-19 01:46 UTC, merged